import type { Metadata } from 'next'
import { EB_Garamond } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'

const garamond = EB_Garamond({subsets: ["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={garamond.className}>
        <div className='flex flex-col h-full w-full min-h-screen bg-teal-950 border-0'>
          <Header />
          <div className='flex'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
